#1. para data ingestion
#key:value

#2. para model preparation se colocan los hiperparámetros
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 2
#usando los pesos de imagenet
WEIGHTS: imagenet 
LEARNING_RATE: 0.01
