artifacts_root: artifacts
#1.
#se crea el directorio artifacts
#dentro de el va a haber otro directorio llamado data ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  #de donde se va a descargar
  source_URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing
  #donde se va a guardar los datos descargados
  local_data_file: artifacts/data_ingestion/data.zip
  #donde de va a guardar los datos descomprimiods
  unzip_dir: artifacts/data_ingestion


#2. para descargar el modelo base y realizar finetune de este
#se va a usar vgg16
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5



#3. donde va a ser almacenado el modelo luego de haber sido entrenado
training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

